name: Cachix
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        # Name of a cachix cache to push and pull/substitute
        name:  math-comp
        # Authentication token for Cachix, needed only for private cache access
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build --arg config '{mathcomp = "1.11.0+beta1"; mathcomp-analysis = "${{GITHUB_REF}}";}' --argstr package mathcomp-analysis
    - run: cachix push math-comp result
